### PR TITLE
feat: get rid of airbnb config; cleanup

### LINKED ISSUE #41: Use `react-app` config instead of AirBnb's
cc @ferrannp

### PR DESCRIPTION
**Pull request by thymikee**
### Summary

- remove airbnb config
- use `eslint:recommended`
- use `plugin:react/recommended `
- cleanup rules (verified what's inside both recommended sets)
- update some deps

Fixes #41 (not quite using `react-app` because it produces warnings around babel parser, but we're quite close I guess?)

### Test plan

Added some

### CODE REVIEW

**Comment by satya164** [comment]
How about hooks? :P

**Comment by thymikee** [comment]
Already there ;)

**Comment by thymikee** [comment]
https://github.com/callstack/eslint-config-callstack/pull/44

**Comment by satya164** [comment]
Oh didn't see 🙈

**Pull request merged**
